# Generated by Django 5.0.6 on 2024-06-29 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plantedtree_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
    ]
